apiVersion: v1
kind: Service
metadata:
  name: homeexpsys-general-service
spec:
  type: LoadBalancer
  selector:
    app: homeexpsys-general
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
